/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "tertiary": "#000000",
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "primary-fixed-dim": "#bec6e0",
        "primary-container": "#131b2e",
        "tertiary-container": "#0b1c30",
        "background": "#f7f9fb",
        "secondary-container": "#316bf3",
        "outline": "#76777d",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#7c839b",
        "on-primary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-tint": "#565e74",
        "inverse-primary": "#bec6e0",
        "surface-variant": "#e0e3e5",
        "on-error": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed-variant": "#38485d",
        "on-surface-variant": "#45464d",
        "on-secondary-container": "#fefcff",
        "primary": "#000000",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "primary-fixed": "#dae2fd",
        "on-tertiary-fixed": "#0b1c30",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#003ea8",
        "inverse-on-surface": "#eff1f3",
        "on-surface": "#191c1e",
        "secondary-fixed": "#dbe1ff",
        "on-primary-fixed-variant": "#3f465c",
        "on-background": "#191c1e",
        "secondary-fixed-dim": "#b4c5ff",
        "tertiary-fixed": "#d3e4fe",
        "secondary": "#0051d5",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container": "#eceef0",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#b7c8e1",
        "outline-variant": "#c6c6cd",
        "on-tertiary-container": "#75859d",
        "on-secondary-fixed": "#00174b"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "component-padding-sm": "8px",
        "component-padding-md": "16px",
        "component-padding-lg": "24px",
        "unit": "8px",
        "gutter": "16px",
        "container-margin": "24px"
      },
      fontFamily: {
        "body-main": ["Inter"],
        "h1": ["Inter"],
        "body-sm": ["Inter"],
        "h3": ["Inter"],
        "label-caps": ["Inter"],
        "technical-data": ["Inter"],
        "h2": ["Inter"]
      },
    },
  },
  plugins: [],
}
